services:
  api_server:
    image: maxutility2011/ezlivestreaming_apiserver
    build: 
      context: .
      dockerfile: ./docker/Dockerfile.server
    volumes:
      - $HOME/.aws/credentials:/home/streamer/.aws/credentials:ro
    ports:
      - "1080:1080"
      - "4080:4080"
    links:
      - "redis:redis"
      - "key_server:key_server"
  scheduler:
    image: maxutility2011/ezlivestreaming_scheduler
    build:
      context: .
      dockerfile: ./docker/Dockerfile.scheduler
    volumes:
      - $HOME/.aws/credentials:/home/streamer/.aws/credentials:ro
    ports:
      - "3080:3080"
    links:
      - "redis:redis"
  key_server:
    image: maxutility2011/ezlivestreaming_keyserver
    build:
      context: .
      dockerfile: ./docker/Dockerfile.keyserver
    ports:
      - "5080:5080"
  redis:
    image: redis
    ports:
      - "6379:6379"
  worker:
    image: maxutility2011/ezlivestreaming_worker
    build:
      context: .
      dockerfile: ./docker/Dockerfile.worker
    volumes:
      - $HOME/.aws/credentials:/home/streamer/.aws/credentials:ro
    ports:
      - "2080:2080"
      - "1935-1950:1935-1950"