FROM maxutility2011/ezlivestreaming_worker_baseimage:v1 as base

RUN mkdir /home/streamer/bin \
    && mkdir /home/streamer/conf \
    && cd /var/www/html/ \
    && git clone https://github.com/maxutility2011/ezLiveStreaming.git 

RUN cd /var/www/html/ezLiveStreaming/worker/app \
    && /usr/local/go/bin/go build worker_app.go \
    && cp /var/www/html/ezLiveStreaming/worker/app/worker_app /home/streamer/bin/ \
    && cp /var/www/html/ezLiveStreaming/worker/app/worker_app_config.json /home/streamer/conf/worker_app_config.json

RUN cd /var/www/html/ezLiveStreaming/worker/transcoder \
    && /usr/local/go/bin/go build worker_transcoder.go \
    && cp /var/www/html/ezLiveStreaming/worker/transcoder/worker_transcoder /home/streamer/bin/ \
    && cp /var/www/html/ezLiveStreaming/worker/transcoder/packager /home/streamer/bin/

ENV PATH="${PATH}:/home/streamer/bin"

EXPOSE 1080
EXPOSE 4080

USER streamer
RUN sudo apt install net-tools
CMD /home/streamer/bin/worker_app -config=/home/streamer/conf/worker_app_config.json
