FROM maxutility2011/ezlivestreaming_baseimage:v3

RUN mkdir /home/streamer/bin \
    && mkdir /home/streamer/conf \
    && cd /var/www/html/ \
    && git clone https://github.com/maxutility2011/ezLiveStreaming.git 

RUN cd /var/www/html/ezLiveStreaming/api_server \
    && /usr/local/go/bin/go build api_server_main.go \
    && cp /var/www/html/ezLiveStreaming/api_server/api_server_main /home/streamer/bin/ \
    && cp /var/www/html/ezLiveStreaming/api_server/config.json /home/streamer/conf/apt_server_config.json \
    && cd ..

RUN cp /var/www/html/ezLiveStreaming/api_server/start_server.sh /home/streamer/bin/ \
    && chmod +x /home/streamer/bin/start_server.sh

ENV PATH="${PATH}:/home/streamer/bin"

EXPOSE 1080
EXPOSE 4080

USER streamer
#RUN sudo apt install net-tools -y
CMD /home/streamer/bin/start_server.sh
