FROM maxutility2011/ezlivestreaming_baseimage:v5.1

USER streamer

RUN mkdir /home/streamer/src \
    && mkdir /home/streamer/bins \
    && mkdir /home/streamer/conf \
    && mkdir /home/streamer/log \
    && cd /home/streamer/src \
    && git clone -b stats https://github.com/maxutility2011/ezLiveStreaming.git 

RUN cd /home/streamer/src/ezLiveStreaming/drm_key_server \
    && /usr/local/go/bin/go build ezKey_server.go \
    && cp /home/streamer/src/ezLiveStreaming/drm_key_server/ezKey_server /home/streamer/bins/ \
    && cp /home/streamer/src/ezLiveStreaming/drm_key_server/config.json /home/streamer/conf/drm_key_server_config.json \
    && cd ..

ENV PATH="${PATH}:/home/streamer/bins"

EXPOSE 5080

CMD /home/streamer/bins/ezKey_server -config=/home/streamer/conf/drm_key_server_config.json
