FROM maxutility2011/ezlivestreaming_baseimage:v4

RUN mkdir /home/streamer/src \
    && mkdir /home/streamer/bin \
    && mkdir /home/streamer/conf \
    && cd /home/streamer/src \
    && git clone https://github.com/maxutility2011/ezLiveStreaming.git 

RUN cd /home/streamer/src/ezLiveStreaming/scheduler \
    && /usr/local/go/bin/go build scheduler.go \
    && cp /home/streamer/src/ezLiveStreaming/scheduler/scheduler /home/streamer/bin/ \
    && cp /home/streamer/src/ezLiveStreaming/scheduler/config.json /home/streamer/conf/scheduler_config.json \
    && cd ..

ENV PATH="${PATH}:/home/streamer/bin"

EXPOSE 3080
USER streamer

CMD /home/streamer/bin/scheduler -config=/home/streamer/conf/scheduler_config.json
