FROM maxutility2011/ezlivestreaming_baseimage:v3

RUN mkdir /home/streamer/src \
    && mkdir /home/streamer/bin \
    && mkdir /home/streamer/conf \
    && mkdir /home/streamer/log \
    && cd /home/streamer/src \
    && git clone https://github.com/maxutility2011/ezLiveStreaming.git 

RUN cd /home/streamer/src/ezLiveStreaming/drm_key_server \
    && /usr/local/go/bin/go build ezKey_server.go \
    && cp /home/streamer/src/ezLiveStreaming/drm_key_server/ezKey_server /home/streamer/bin/ \
    && cp /home/streamer/src/ezLiveStreaming/drm_key_server/config.json /home/streamer/conf/drm_key_server_config.json \
    && cd ..

ENV PATH="${PATH}:/home/streamer/bin"

EXPOSE 5080

USER streamer
#RUN sudo apt install net-tools -y
CMD /home/streamer/bin/ezKey_server -config=/home/streamer/conf/drm_key_server_config.json
