FROM maxutility2011/ezlivestreaming_baseimage:v5.1

USER streamer

RUN mkdir /home/streamer/src \
    && mkdir /home/streamer/bins \
    && mkdir /home/streamer/conf \
    && mkdir /home/streamer/log \
    && cd /home/streamer/src \
    && git clone -b bugfixes_1 https://github.com/maxutility2011/ezLiveStreaming.git 

RUN cd /home/streamer/src/ezLiveStreaming/scheduler \
    && /usr/local/go/bin/go build scheduler.go \
    && cp /home/streamer/src/ezLiveStreaming/scheduler/scheduler /home/streamer/bins/ \
    && cd ..

COPY ../scheduler/config.json /home/streamer/conf/scheduler_config.json

ENV PATH="${PATH}:/home/streamer/bins"

EXPOSE 3080

CMD /home/streamer/bins/scheduler -config=/home/streamer/conf/scheduler_config.json
