FROM maxutility2011/ezlivestreaming_baseimage:v5

USER streamer

RUN mkdir /home/streamer/bin \
    && mkdir /home/streamer/conf \
    && mkdir /home/streamer/src \
    && cd /home/streamer/src \
    && git clone https://github.com/maxutility2011/ezLiveStreaming.git \
    && sudo cp -rf /home/streamer/src/ezLiveStreaming/demo /var/www/html/

RUN cd /home/streamer/src/ezLiveStreaming/api_server \
    && /usr/local/go/bin/go build api_server_main.go \
    && cp /home/streamer/src/ezLiveStreaming/api_server/api_server_main /home/streamer/bin/ \
    && cp /home/streamer/src/ezLiveStreaming/api_server/config.json /home/streamer/conf/apt_server_config.json \
    && cd ..

RUN cp /home/streamer/src/ezLiveStreaming/api_server/start_server.sh /home/streamer/bin/ \
    && chmod +x /home/streamer/bin/start_server.sh

ENV PATH="${PATH}:/home/streamer/bin"

EXPOSE 1080
EXPOSE 4080

#CMD /home/streamer/bin/start_server.sh
